### ISSUE TITLE
interactive application and loading package into R issues

### ISSUE THREAD

**Issue by buckyeahice** [cran/StepReg#2]
hello! i'm a little bit new at this (and raising issues), so please let me know if more information is required from me!

i accessed the stepreg interactive application and was trying it out with the example "lung" dataset to run it with the cox regression type. however, it seems to run well with the exception if i also included any other 'included variables', to which is fails and showcases:

`"An error has occurred. Check your logs or contact the app author for clarification."`

here is are the variables that i tried it out as an example:
![Screenshot 2024-05-07 at 5 22 22 AM](https://github.com/cran/StepReg/assets/111502914/c5b84c0c-16fb-4240-aa98-822f9f73d367)

what might have been the case? 

also, i wanted to run it in R but after downloading the package, i couldn't load it as it aborts my R session entirely. would there be any reason why this might be the case? i am using a mac sonoma 14.5 with R 4.3.1!

thank you very much in advance!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by JunhuiLi1017** [comment]
Hi @buckyeahice , please try to install the version using the following code `devtools::install_github("JunhuiLi1017/StepReg", ref="dev", force = TRUE)`, this issue should be addressed.

Junhui

**Comment by buckyeahice** [comment]
ah thank you! it worked :)
