### ISSUE TITLE
Error when combining strategy='subset' and include argument

### ISSUE THREAD

**Issue by TimZaragori** [cran/StepReg#3]
Running `stepwise` with `strategy="subset"` and using the `include` argument (ex `include=c(var1,var2)`) returns an error.

Here is a reproducible example

```
data(mtcars)

formula <- mpg ~ .

# This is OK
res1 <- stepwise(formula = formula,
                 data = mtcars,
                 type = "linear",
                 include = c("disp", "cyl"),
                 strategy = "forward",
                 metric = "AIC")

# This returns an error
res1 <- stepwise(formula = formula,
                 data = mtcars,
                 type = "linear",
                 include = c("disp", "cyl"),
                 strategy = "subset",
                 metric = "AIC")
```
Please find below the error:
`'names' attribute [2] must be the same length as the vector [1]`

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
